# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4fd9d0d1414b51934810f69199e32bb3e660220e143bb7dd58bdd7762b3c7cf2dc61db61319e807e413e9ad95bacb9a2aa4a2c02de692eebf6bad83b6b89ab2

test:
  secret_key_base: 39d7b03a8e291cc36a8084c352790e7495f50b9a5e5f351f13bf9296027615299e3105382c6f897d490e8d20cadce2566a5d26f619f49dad1e93a006c29abefd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
